### ISSUE TITLE
Question: using filter and multiline codecs together.

### ISSUE THREAD

**Issue by PMDubuc** [driskell/log-courier#320]
I want to use your multiline and filter codecs together to combine events into multiline events and then filter out any events, single or multiline, that match a pattern so that they aren't shipped.  I don't think that is what is being done in the example you give for multiple codecs, so I wonder if this example will work to ignore any message that has the string "|DEBUG|" in it:

```
admin:
    enabled: true
network:
    servers:
        - localhost:5043
    ssl ca: ./logstash.cer
files:
  - paths:
        - /var/log/httpd/error.log
    fields:
        type: errors
    codecs:
        - name: multiline
            patterns:
                  - "!^[0-9]{4}/[0-9]{2}/[0-9]{2} [0-9]{2}:[0-9]{2}:[0-9]{2} "
            what: previous
        - name: filter:
             patterns:
                  - "!(.*\\|DEBUG\\|.*)"
```
