### ISSUE TITLE
Please support include configuration file with some global settings

### ISSUE THREAD

**Issue by jindov** [driskell/log-courier#337]
Please support include configuration like nginx with global and specified settings, ie:
I have a global configuration:
log-courier.conf:
```
network:
  ssl ca: /etc/log-courier/logstash.cer
  method: loadbalance
files:
  fields:
  type: nginx
general:
  log level: debug
  log syslog: true
includes:
  - /etc/log-courier/conf.d/specific.conf
  - /etc/log-courier/conf.d/specific1.conf
```
specific.conf:
```
network:
  servers:
     - "log01:5043"
     - "log02:5043"
files:
  paths:
     - /var/log/nginx/json/file_a.json.log
```
```
specific1.conf:
network:
  servers:
     - "log01:5044"
     - "log02:5044"
files:
  paths:
     - /var/log/nginx/json/file_b.json.log
```
thank you for reading
